src/api/urls.py
from api.views import BbDetailView
from api.views import bbs
from api.views import comments
from django.urls import path

urlpatterns = [
    path("bbs/<int:pk>/comments/", comments),
    path("bbs/<int:pk>/", BbDetailView.as_view()),
    path("bbs/", bbs),
]

src/core/urls.py
from core import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.views import serve
from django.urls import include
from django.urls import path
from django.views.decorators.cache import never_cache

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("users.urls")),
    path("api/", include("api.urls")),
    path("captcha/", include("captcha.urls")),
    path("", include("bboard.urls")),
]

if settings.DEBUG:
    urlpatterns.append(path("static/<path:path>", never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.urls import include
from django.urls import path
from users.views import BBLoginView
from users.views import BBLogoutView
from users.views import BBPasswordChangeView
from users.views import BBPasswordResetCompleteView
from users.views import BBPasswordResetConfirmView
from users.views import BBPasswordResetDoneView
from users.views import BBPasswordResetView
from users.views import ChangeUserInfoView
from users.views import DeleteUserView
from users.views import profile
from users.views import profile_bb_add
from users.views import profile_bb_change
from users.views import profile_bb_delete
from users.views import profile_bb_detail
from users.views import RegisterDoneView
from users.views import RegisterUserView
from users.views import user_activate

app_name = "users"
urlpatterns = [
    path(
        "register/",
        include(
            [
                path(
                    "activate/<str:sign>/",
                    user_activate,
                    name="register_activate",
                ),
                path("done/", RegisterDoneView.as_view(), name="register_done"),
                path("", RegisterUserView.as_view(), name="register"),
            ]
        ),
    ),
    path(
        "profile/",
        include(
            [
                path(
                    "change/",
                    ChangeUserInfoView.as_view(),
                    name="profile_change",
                ),
                path("delete/", DeleteUserView.as_view(), name="profile_delete"),
                path("change/<int:pk>/", profile_bb_change, name="profile_bb_change"),
                path("delete/<int:pk>/", profile_bb_delete, name="profile_bb_delete"),
                path("add/", profile_bb_add, name="profile_bb_add"),
                path("<int:pk>/", profile_bb_detail, name="profile_bb_detail"),
                path("", profile, name="profile"),
            ]
        ),
    ),
    path(
        "password/",
        include(
            [
                path(
                    "reset/",
                    include(
                        [
                            path(
                                "done/",
                                BBPasswordResetDoneView.as_view(),
                                name="password_reset_done",
                            ),
                            path(
                                "confirm/<uidb64>/<token>/",
                                BBPasswordResetConfirmView.as_view(),
                                name="password_reset_confirm",
                            ),
                            path(
                                "complete/",
                                BBPasswordResetCompleteView.as_view(),
                                name="password_reset_complete",
                            ),
                            path(
                                "", BBPasswordResetView.as_view(), name="password_reset"
                            ),
                        ]
                    ),
                ),
                path(
                    "change/",
                    BBPasswordChangeView.as_view(),
                    name="password_change",
                ),
            ]
        ),
    ),
    path("login/", BBLoginView.as_view(), name="login"),
    path("logout/", BBLogoutView.as_view(), name="logout"),
]

src/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class AdvUser(AbstractUser):
    is_activated = models.BooleanField(
        default=True, db_index=True, verbose_name="Прошел активацию?"
    )
    send_massages = models.BooleanField(
        default=True, verbose_name="Слать оповещения о новых коментариях?"
    )

    def delete(self, using=None, keep_parents=False):
        for bb in self.bb_set.all():
            bb.delete()
        super().delete()

    class Meta:
        pass

src/users/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import PasswordResetForm
from django.core.exceptions import ValidationError
from users.apps import user_registered
from users.models import AdvUser


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label="Адрес электронной почты")
    password1 = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label="Пароль (повторно)",
        widget=forms.PasswordInput,
        help_text="Введите тот же самый пароль еще раз для проверки",
    )

    def clean_password1(self):
        password1 = self.cleaned_data["password1"]
        if password1:
            password_validation.validate_password(password1)
        return password1

    def clean(self):
        super().clean()
        user = AdvUser.objects.filter(email=self.cleaned_data["email"])
        if user:
            errors = {
                "email": ValidationError(
                    "Пользователь с таким email уже зарегестрирован",
                    code="email_registered",
                )
            }
            raise ValidationError(errors)
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]
        if password1 and password2 and password1 != password2:
            errors = {
                "password2": ValidationError(
                    "Введенные пароли не совпадают", code="password_mismatch"
                )
            }
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_activated = False
        user.is_active = False
        if commit:
            user.save()
        user_registered.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = AdvUser
        fields = (
            "username",
            "email",
            "password1",
            "password2",
            "first_name",
            "last_name",
            "send_massages",
        )


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True, label="Адрес электронной почты")

    class Meta:
        model = AdvUser
        fields = ("username", "email", "first_name", "last_name", "send_massages")


class UsersPasswordResetForm(PasswordResetForm):
    def clean(self):
        super().clean()
        user = AdvUser.objects.filter(email=self.cleaned_data["email"])
        if not user:
            errors = {
                "email": ValidationError(
                    "Пользователь с таким email не зарегестрирован",
                    code="email_not_found",
                )
            }
            raise ValidationError(errors)


class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=20, label="")

src/users/views.py
from bboard.form import AIFormSet
from bboard.form import BbForm
from bboard.models import Bb
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.signing import BadSignature
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import TemplateView
from django.views.generic import UpdateView
from users.forms import ChangeUserInfoForm
from users.forms import RegisterUserForm
from users.forms import UsersPasswordResetForm
from users.models import AdvUser
from users.utilities import signer


@login_required
def profile(request):
    bbs = Bb.objects.filter(author=request.user.pk)
    context = {"bbs": bbs}
    return render(request, "users/profile.html", context)


@login_required
def profile_bb_detail(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    ais = bb.additionalimage_set.all()
    context = {"bb": bb, "ais": ais}
    return render(request, "users/bb_detail.html", context)


@login_required
def profile_bb_add(request):
    if request.method == "POST":
        form = BbForm(request.POST, request.FILES)
        if form.is_valid():
            bb = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, "Обьявление добавлено")
                return redirect("users:profile")
    else:
        form = BbForm(initial={"author": request.user.pk})
        formset = AIFormSet()
        context = {"form": form, "formset": formset}
        return render(request, "users/profile_bb_add.html", context)


@login_required
def profile_bb_delete(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    if request.method == "POST":
        bb.delete()
        messages.add_message(request, messages.SUCCESS, "Обьявление удалено")
        return redirect("users:profile")
    else:
        context = {"bb": bb}
        return render(request, "users/profile_bb_delete.html", context)


@login_required
def profile_bb_change(request, pk):
    bb = get_object_or_404(Bb, pk=pk)
    if request.method == "POST":
        form = BbForm(request.POST, request.FILES, instance=bb)
        if form.is_valid():
            form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=bb)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, "Обьявление исправлено")
                return redirect("users:profile")
    else:
        form = BbForm(instance=bb)
        formset = AIFormSet(instance=bb)
        context = {"form": form, "formset": formset}
        return render(request, "users/profile_bb_change.html", context)


def user_activate(request, sign):
    try:
        username = signer.unsign(sign)
    except BadSignature:
        return render(request, "users/bad_signature.html")
    user = get_object_or_404(AdvUser, username=username)
    if user.is_activated:
        template = "users/user_is_activated.html"
    else:
        template = "users/activation_done.html"
        user.is_activated = True
        user.is_active = True
        user.save()
    return render(request, template)


class BBLoginView(LoginView):
    template_name = "users/login.html"


class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = "users/logout.html"


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = AdvUser
    form_class = ChangeUserInfoForm
    template_name = "users/change_user_info.html"
    success_url = reverse_lazy("users:profile")
    success_message = "Данные пользователя изменены"

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class BBPasswordChangeView(SuccessMessageMixin, LoginRequiredMixin, PasswordChangeView):
    template_name = "users/password_change.html"
    success_url = reverse_lazy("users:profile")
    success_message = "Пароль пользователя изменен"


class BBPasswordResetView(PasswordResetView):
    form_class = UsersPasswordResetForm
    template_name = "users/password_reset.html"
    email_template_name = "email/password_reset_email.txt"
    success_url = reverse_lazy("users:password_reset_done")


class BBPasswordResetDoneView(PasswordResetDoneView):
    template_name = "users/password_reset_done.html"


class BBPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = "users/password_reset_confirm.html"
    success_url = reverse_lazy("users:password_reset_complete")


class BBPasswordResetCompleteView(TemplateView):
    template_name = "users/password_reset_complete.html"


class RegisterUserView(CreateView):
    model = AdvUser
    template_name = "users/register_user.html"
    form_class = RegisterUserForm
    success_url = reverse_lazy("users:register_done")


class RegisterDoneView(TemplateView):
    template_name = "users/register_done.html"


class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = "users/delete_user.html"
    success_url = reverse_lazy("bboard:index")

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, "Пользователь успешно удален!")
        return super().post(self, request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

src/users/templates/users/bad_signature.html
{% extends "layout/basic.html" %}

{% block title %}
    Ошибка при активации
{% endblock %}

{% block content %}
    <h2>Активация</h2>
    <p>Активация пользователя с таким именем прошла неудачно.</p>
    <p><a href="{% url "users:register" %}">Зарегестрироваться повторно</a></p>
{% endblock %}

src/users/templates/users/bb_detail.html
{% extends "layout/basic.html" %}

{% block title %}
    {{ bb.title }} - {{ bb.rubric.name }}
{% endblock %}

{% block content %}
    <div class="container-fluid mt-3">
        <div class="row">
            {% if bb.image %}
                <div class="col-md-auto"><img src="{{ bb.image.url }}" class="main-image"></div>
            {% endif %}
            <div class="col">
                <h2>{{ bb.title }}</h2>
                <p>{{ bb.content }}</p>
                <p class="font-weight-bold">{{ bb.price }} руб.</p>
                <p class="text-right font-italic">Добавлено {{ bb.created_at }}</p>
            </div>
        </div>
    </div>
    {% if ais %}
        <div class="d-flex justify-content-between flex-wrap mt-5">
            {% for ai in ais %}
                <div>
                    <img src="{{ ai.image.url }}" class="additional-image">
                </div>
            {% endfor %}
        </div>
    {% endif %}
<p><a href="{% url "users:profile" %}{{ all }}">Назад</a></p>
{% endblock %}

src/users/templates/users/delete_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}
    Удаление пользователя
{% endblock %}

{% block content %}
    <h2>Удаление пользователя {{ object.username }}</h2>
    <form method="post">
    {% csrf_token %}
    {% buttons submit="Удалить" %}{% endbuttons %}
    </form>
{% endblock %}

src/users/templates/users/login.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}
{% block title %}
    Вход
{% endblock %}

{% block content %}
    <h2>Вход</h2>
    {% if user.is_authenticated %}
        <p>Вы уже выполнили вход.</p>
    {% else %}
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form layout='horizontal' %}
            <input type="hidden" name="next" value="{{ next }}">
                {% buttons submit='Войти' %}{% endbuttons %}
        <p><a href="{% url "users:password_reset" %}">Забыл пароль?</a></p>
        </form>
    {% endif %}
{% endblock %}

src/users/templates/users/logout.html
{% extends "layout/basic.html" %}

{% block title %}
    Выход
{% endblock %}

{% block content %}
    <h2>Выход</h2>
    <p>Вы успешно вышли с сайта.</p>
{% endblock %}

src/users/templates/users/password_change.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}

{% block title %}
    Смена пароля
{% endblock %}

{% block content %}
    <h2>Смена пароля пользователя {{ user.username }}</h2>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Сменить пароль' %}{% endbuttons %}
    </form>
{% endblock %}

src/users/templates/users/password_reset_complete.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}

{% block title %}
    Пароль изменен
{% endblock %}

{% block content %}
    <h2>Пароль изменен</h2>
    <p>Вы можете <a href="{% url "users:login" %}">войти</a> в аккаунт используя новый пароль.</p>
{% endblock %}

src/users/templates/users/password_reset_confirm.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}

{% block title %}
    Сброс пароля
{% endblock %}

{% block content %}
    <h2>Сброс пароля</h2>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Отправить' %}{% endbuttons %}
    </form>
{% endblock %}

src/users/templates/users/password_reset_done.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}

{% block title %}
    Сброс пароля
{% endblock %}

{% block content %}
    <h2>Сброс пароля</h2>
    <p>На вашу электронную почту отправлено письмо со ссылкой для подтверждения, проверьте почту!</p>
{% endblock %}

src/users/templates/users/profile.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}
{% load thumbnail %}
{% load static %}


{% block title %}
    Профиль пользователя
{% endblock %}

{% block content %}
    <h2>
        Профиль пользователя {{ user.username }}
    </h2>

    {% if user.first_name and user.last_name %}
        <p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
    {% else %}
        <p>Здравствуйте!</p>
    {% endif %}
    <h3 class="mb-2">Ваши обьявления</h3>
    <p><a href="{% url 'users:profile_bb_add' %}">Добавить обьявление</a></p>
    <div class="container-fluid mb-2">
        <div class="row">
            <div class="col">&nbsp;</div>
        </div>
    </div>
    {% if bbs %}
        <ul class="list-unstyled">
            {% for bb in bbs %}
                <li class="media my-5 p-3 border">
                    {% url "users:profile_bb_detail" pk=bb.pk as url %}
                    <a href="{{ url }}{{ all }}">
                        {% if bb.image %}
                            <img class="mr-3" src="{% thumbnail bb.image 'default' %}">
                        {% else %}
                            <img src="{% static 'bboard/empty.jpg' %}" width="200">
                        {% endif %}
                    </a>
                    <div class="media-body">
                        <h3><a href="{{ url }}{{ all }}">{{ bb.title }}</a></h3>
                        <div>{{ bb.content }}</div>
                        <p class="text-right font-weight-bold">{{ bb.price }} руб.</p>
                        <p class="text-right font-italic">{{ bb.created_at }}</p>
                        <p class="text-right mt-2">
                            <a href="{% url 'users:profile_bb_change' pk=bb.pk %}">Изменить</a>
                            <a href="{% url 'users:profile_bb_delete' pk=bb.pk %}">Удалить</a>
                        </p>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

src/users/templates/users/profile_bb_add.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}
    Добавление обьявления - Профиль пользователя
{% endblock %}

{% block content %}
    <h2>Добавление обьявления</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% bootstrap_formset formset layout="horizontal" %}
        {% buttons submit="Добавить" %}{% endbuttons %}
    </form>
{% endblock %}

src/users/templates/users/profile_bb_change.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}
    Изменение обьявления - Профиль пользователя
{% endblock %}

{% block content %}
    <h2>Изменение обьявления</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% bootstrap_formset formset layout="horizontal" %}
        {% buttons submit="Изменить" %}{% endbuttons %}
    </form>
{% endblock %}

src/users/templates/users/profile_bb_delete.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}
    Удаление обьявления - {{ bb.title }}
{% endblock %}

{% block content %}
    <div class="container-fluid mt-3">
        <div class="row">
            {% if bb.image %}
                <div class="col-md-auto"><img src="{{ bb.image.url }}" class="main-image"></div>
            {% endif %}
            <div class="col">
                <h2>{{ bb.title }}</h2>
                <p>{{ bb.content }}</p>
                <p class="font-weight-bold">{{ bb.price }} руб.</p>
                <p class="text-right font-italic">Добавлено {{ bb.created_at }}</p>
            </div>
        </div>
    </div>
    <form method="POST">
        {% csrf_token %}
        {% buttons submit="Удалить" pk=bb.pk %}{% endbuttons %}
    </form>
    <p><a href="{% url "users:profile" %}">Назад</a></p>
{% endblock %}

src/users/templates/users/register_user.html
{% extends "layout/basic.html" %}
{% load bootstrap4 %}

{% block title %}
    Регистрация
{% endblock %}

{% block content %}
    <h2>Регистрация нового пользователя</h2>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit='Зарегестрироваться' %}{% endbuttons %}
    </form>
{% endblock %}