src/api/urls.py
from api.views import BbDetailView
from api.views import bbs
from api.views import comments
from django.urls import path

urlpatterns = [
    path("bbs/<int:pk>/comments/", comments),
    path("bbs/<int:pk>/", BbDetailView.as_view()),
    path("bbs/", bbs),
]

src/bboard/urls.py
from bboard.views import by_rubric
from bboard.views import detail
from bboard.views import index
from bboard.views import other_page
from django.urls import path

app_name = "bboard"

urlpatterns = [
    path("<int:rubric_pk>/<int:pk>/", detail, name="detail"),
    path("<int:pk>/", by_rubric, name="by_rubric"),
    path("<str:page>/", other_page, name="other"),
    path("", index, name="index"),
]

src/core/urls.py
from core import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.views import serve
from django.urls import include
from django.urls import path
from django.views.decorators.cache import never_cache

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("users.urls")),
    path("api/", include("api.urls")),
    path("captcha/", include("captcha.urls")),
    path("", include("bboard.urls")),
]

if settings.DEBUG:
    urlpatterns.append(path("static/<path:path>", never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/urls.py
from django.urls import include
from django.urls import path
from users.views import BBLoginView
from users.views import BBLogoutView
from users.views import BBPasswordChangeView
from users.views import BBPasswordResetCompleteView
from users.views import BBPasswordResetConfirmView
from users.views import BBPasswordResetDoneView
from users.views import BBPasswordResetView
from users.views import ChangeUserInfoView
from users.views import DeleteUserView
from users.views import profile
from users.views import profile_bb_add
from users.views import profile_bb_change
from users.views import profile_bb_delete
from users.views import profile_bb_detail
from users.views import RegisterDoneView
from users.views import RegisterUserView
from users.views import user_activate

app_name = "users"
urlpatterns = [
    path(
        "register/",
        include(
            [
                path(
                    "activate/<str:sign>/",
                    user_activate,
                    name="register_activate",
                ),
                path("done/", RegisterDoneView.as_view(), name="register_done"),
                path("", RegisterUserView.as_view(), name="register"),
            ]
        ),
    ),
    path(
        "profile/",
        include(
            [
                path(
                    "change/",
                    ChangeUserInfoView.as_view(),
                    name="profile_change",
                ),
                path("delete/", DeleteUserView.as_view(), name="profile_delete"),
                path("change/<int:pk>/", profile_bb_change, name="profile_bb_change"),
                path("delete/<int:pk>/", profile_bb_delete, name="profile_bb_delete"),
                path("add/", profile_bb_add, name="profile_bb_add"),
                path("<int:pk>/", profile_bb_detail, name="profile_bb_detail"),
                path("", profile, name="profile"),
            ]
        ),
    ),
    path(
        "password/",
        include(
            [
                path(
                    "reset/",
                    include(
                        [
                            path(
                                "done/",
                                BBPasswordResetDoneView.as_view(),
                                name="password_reset_done",
                            ),
                            path(
                                "confirm/<uidb64>/<token>/",
                                BBPasswordResetConfirmView.as_view(),
                                name="password_reset_confirm",
                            ),
                            path(
                                "complete/",
                                BBPasswordResetCompleteView.as_view(),
                                name="password_reset_complete",
                            ),
                            path(
                                "", BBPasswordResetView.as_view(), name="password_reset"
                            ),
                        ]
                    ),
                ),
                path(
                    "change/",
                    BBPasswordChangeView.as_view(),
                    name="password_change",
                ),
            ]
        ),
    ),
    path("login/", BBLoginView.as_view(), name="login"),
    path("logout/", BBLogoutView.as_view(), name="logout"),
]

src/bboard/models.py
from bboard.utilities import get_timestamp_path
from django.db import models
from users.models import AdvUser


class SuperRubricManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_rubric__isnull=True)


class SubRubricManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(super_rubric__isnull=False)


class Bb(models.Model):
    rubric = models.ForeignKey(
        "SubRubric", on_delete=models.PROTECT, verbose_name="Рубрика"
    )
    title = models.CharField(max_length=40, verbose_name="Товар")
    content = models.TextField(verbose_name="Описание")
    price = models.FloatField(default=0, verbose_name="Цена")
    contacts = models.TextField(verbose_name="Контакты")
    image = models.ImageField(
        blank=True, upload_to=get_timestamp_path, verbose_name="Изображение"
    )
    author = models.ForeignKey(
        AdvUser, on_delete=models.CASCADE, verbose_name="Автор обьявления"
    )
    is_active = models.BooleanField(
        default=True, db_index=True, verbose_name="Выводить в списке?"
    )
    created_at = models.DateTimeField(
        auto_now_add=True, db_index=True, verbose_name="Опубликовано"
    )

    def delete(self, using=None, keep_parents=False):
        for ai in self.additionalimage_set.all():
            ai.delete()
        super().delete()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Обьявление"
        verbose_name_plural = "Обьявления"
        ordering = ("-created_at",)


class AdditionalImage(models.Model):
    bb = models.ForeignKey(Bb, on_delete=models.CASCADE, verbose_name="Обьявление")
    image = models.ImageField(upload_to=get_timestamp_path, verbose_name="Изображение")

    class Meta:
        verbose_name = "Дополнительная илюстрация"
        verbose_name_plural = "Дополнительные илюстрации"


class Rubric(models.Model):
    name = models.CharField(
        max_length=20, unique=True, db_index=True, verbose_name="Название"
    )
    order = models.SmallIntegerField(default=0, db_index=True, verbose_name="Порядок")
    super_rubric = models.ForeignKey(
        "SuperRubric",
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        verbose_name="Надрубрика",
    )


class SuperRubric(Rubric):
    objects = SuperRubricManager()

    def __str__(self):
        return self.name

    class Meta:
        proxy = True
        ordering = (
            "order",
            "name",
        )
        verbose_name = "Надрубрика"
        verbose_name_plural = "Надрубрики"


class SubRubric(Rubric):
    objects = SubRubricManager()

    def __str__(self):
        return "%s - %s" % (self.super_rubric.name, self.name)

    class Meta:
        proxy = True
        ordering = (
            "super_rubric__order",
            "super_rubric__name",
            "order",
            "name",
        )
        verbose_name = "Подрубрика"
        verbose_name_plural = "Подрубрики"

src/bboard/views.py
from bboard.models import Bb
from bboard.models import SubRubric
from comments.forms import GuestCommentForm
from comments.forms import UserCommentForm
from comments.models import Comment
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from users.forms import SearchForm


def index(request):
    bbs = Bb.objects.filter(is_active=True)[:10]
    context = {"bbs": bbs}
    return render(request, "bboard/index.html", context)


def other_page(request, page):
    try:
        template = get_template("bboard/" + page + ".html")
    except TemplateDoesNotExist:
        raise Http404
    return HttpResponse(template.render(request=request))


def by_rubric(request, pk):
    rubric = get_object_or_404(SubRubric, pk=pk)
    bbs = Bb.objects.filter(is_active=True, rubric=pk)
    if "keyword" in request.GET:
        keyword = request.GET["keyword"]
        q = Q(title__icontains=keyword) | Q(content__icontains=keyword)
        bbs = bbs.filter(q)
    else:
        keyword = ""
    form = SearchForm(initial={"keyword": keyword})
    paginator = Paginator(bbs, 2)
    if "page" in request.GET:
        page_num = request.GET["page"]
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {"rubric": rubric, "page": page, "bbs": page.object_list, "form": form}
    return render(request, "bboard/by_rubric.html", context)


def detail(request, rubric_pk, pk):
    bb = get_object_or_404(Bb, pk=pk)
    ais = bb.additionalimage_set.all()
    comments = Comment.objects.filter(bb=pk, is_active=True)
    initial = {"bb": bb.pk}

    if request.user.is_authenticated:
        initial["author"] = request.user.username
        form_class = UserCommentForm
    else:
        form_class = GuestCommentForm

    form = form_class(initial=initial)
    if request.method == "POST":
        c_form = form_class(request.POST)
        if c_form.is_valid():
            c_form.save()
            messages.add_message(request, messages.SUCCESS, "Коментарий добавлен")
        else:
            form = c_form
            messages.add_message(request, messages.WARNING, "Коментарий не добавлен")
    context = {"bb": bb, "ais": ais, "comments": comments, "form": form}
    return render(request, "bboard/detail.html", context)

src/bboard/templates/bboard/about.html
{% extends "layout/basic.html" %}
{% block title %}О сайте{% endblock %}
{% block content%}
    <h2>О сайте</h2>
    <p>Сайт для публикаций обьявлений о продаже, разбитых на рубрики</p>
{% endblock %}

src/bboard/templates/bboard/activation_done.html
{% extends "layout/basic.html" %}

{% block title %}
    Активация выполнена
{% endblock %}

{% block content %}
    <h2>Активация</h2>
    <p>Пользователь с таким именем успешно активирован.</p>
    <p><a href="{% url "bboard:login" %}">Войти на сайт</a></p>
{% endblock %}

src/bboard/templates/bboard/bad_signature.html
{% extends "layout/basic.html" %}

{% block title %}
    Ошибка при активации
{% endblock %}

{% block content %}
    <h2>Активация</h2>
    <p>Активация пользователя с таким именем прошла неудачно.</p>
    <p><a href="{% url "bboard:register" %}">Зарегестрироваться повторно</a></p>
{% endblock %}

src/bboard/templates/bboard/by_rubric.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}
{% load thumbnail %}
{% load static %}

{% block title %}
    {{ rubric }}
{% endblock %}

{% block content %}
    <h2 class="mb-2">{{ rubric }}</h2>
    <div class="container-fluid mb-2">
        <div class="row">
            <div class="col">&nbsp;</div>
            <form class="col-md-auto form-inline">
                {% bootstrap_form form show_label=False %}
                {% bootstrap_button content="Искать" button_type="submit" %}
            </form>
        </div>
    </div>
    {% if bbs %}
        <ul class="list-unstyled">
            {% for bb in bbs %}
                <li class="media my-5 p-3 border">
                    {% url "bboard:detail" rubric_pk=rubric.pk pk=bb.pk as url %}
                    <a href="{{ url }}{{ all }}">
                        {% if bb.image %}
                            <img class="mr-3" src="{% thumbnail bb.image 'default' %}">
                        {% else %}
                            <img src="{% static 'bboard/empty.jpg' %}" width="200">
                        {% endif %}
                    </a>
                    <div class="media-body">
                        <h3><a href="{{ url }}{{ all }}">{{ bb.title }}</a></h3>
                        <div>{{ bb.content }}</div>
                        <p class="text-right font-weight-bold">{{ bb.price }} руб.</p>
                        <p class="text-right font-italic">{{ bb.created_at }}</p>
                    </div>
                </li>
            {% endfor %}
        </ul>
        {% bootstrap_pagination page url=keyword %}
    {% endif %}
{% endblock %}

src/bboard/templates/bboard/detail.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}
    {{ bb.title }} - {{ bb.rubric.name }}
{% endblock %}

{% block content %}
    <div class="container-fluid mt-3">
        <div class="row">
            {% if bb.image %}
                <div class="col-md-auto"><img src="{{ bb.image.url }}" class="main-image"></div>
            {% endif %}
            <div class="col">
                <h2>{{ bb.title }}</h2>
                <p>{{ bb.content }}</p>
                <p class="font-weight-bold">{{ bb.price }} руб.</p>
                <p class="text-right font-italic">Добавлено {{ bb.created_at }}</p>
            </div>
        </div>
    </div>
    {% if ais %}
        <div class="d-flex justify-content-between flex-wrap mt-5">
            {% for ai in ais %}
                <div>
                    <img src="{{ ai.image.url }}" class="additional-image">
                </div>
            {% endfor %}
        </div>
    {% endif %}
    <p><a href="{% url "bboard:by_rubric" pk=bb.rubric.pk %}{{ all }}">Назад</a></p>
    <h4 class="mt-5">Новый коментарий</h4>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form layout='horizontal' %}
        {% buttons submit="Добавить" %}{% endbuttons %}
    </form>
    {% if comments %}
        <div class="mt-5">
            {% for comment in comments %}
                <div class="my-2 p-2 border">
                    <h5>{{ comment.author }}</h5>
                    <p>{{ comment.content }}</p>
                    <p class="text-right font-italic">{{ comment.created_at }}</p>
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}

src/bboard/templates/bboard/index.html
{% extends "layout/basic.html" %}
{% block content %}
    <h2>Последние 10 обьявлений</h2>
{% endblock %}

src/bboard/templates/bboard/user_is_activated.html
{% extends "layout/basic.html" %}

{% block title %}
    Пользователь уже активирован
{% endblock %}

{% block content %}
    <h2>Активация</h2>
    <p>Пользователь с таким именем уже был активирован ранее.</p>
    <p><a href="{% url "bboard:login" %}">Войти на сайт</a></p>
{% endblock %}